### ISSUE TITLE
Any plans to source open

### ISSUE THREAD

**Issue by hppy139** [WilliamsToTo/causalscore_dialogue#1]
Thanks to the paper.
Will you share the training and infering script, as well as checkpoints?

**Comment by WilliamsToTo** [comment]
The training and inference scripts are available in the `scripts` folder. Dataset-specific checkpoints can be accessed at the following links:

- [[ESConv Dependent Classifier](https://huggingface.co/WilliamsToTo/roberta_ESConv_dependent_classifier)](https://huggingface.co/WilliamsToTo/roberta_ESConv_dependent_classifier)  
- [[ESConv Conditional CI Classifier](https://huggingface.co/WilliamsToTo/roberta_ESConv_conditionalCI_classifier)](https://huggingface.co/WilliamsToTo/roberta_ESConv_conditionalCI_classifier)  
- [[DREAM Dependent Classifier](https://huggingface.co/WilliamsToTo/roberta_dream_dependent_classifier)](https://huggingface.co/WilliamsToTo/roberta_dream_dependent_classifier)  
- [[DREAM Conditional CI Classifier](https://huggingface.co/WilliamsToTo/roberta_dream_conditionalCI_classifier)](https://huggingface.co/WilliamsToTo/roberta_dream_conditionalCI_classifier)  
- [[MSC Dependent Classifier](https://huggingface.co/WilliamsToTo/roberta_msc_dependent_classifier)](https://huggingface.co/WilliamsToTo/roberta_msc_dependent_classifier)  
- [[MSC Conditional CI Classifier](https://huggingface.co/WilliamsToTo/roberta_msc_conditionalCI_classifier)](https://huggingface.co/WilliamsToTo/roberta_msc_conditionalCI_classifier)  

These checkpoints are tailored to specific datasets. For use with other datasets beyond ESConv, DREAM, and MSC, fine-tuning on the new datasets may be required.
